openapi: 3.0.3
info:
  title: File manager API
  description: File manager specification
  contact:
    name: Oleg
    url: https://github.com/a-oleg
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1/
    description: Dev server
tags:
  - name: audio files
    description: tag for working with audio files
paths:
  /audiofiles:
    post:
      tags:
        - audio files
      summary: Save an audio file
      description: Save a new audio file in the database
      operationId: saveAudioFile
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The audio file to upload
                  example: myAudioFile.mp3
                  maxLength: 104857600  # max 100MB
      responses:
        '201':
          description: File successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  fileId:
                    type: string
                    description: The ID of the uploaded file
                    example: 987654321
        '400':
          description: Bad request - invalid file format or missing file
        '413':
          description: Payload too large - file exceeds the 100 MB limit
        '422':
          description: Unprocessable entity - validation error on file upload
        '500':
          description: An internal server error occurred. Please try again later
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"

    get:
      tags:
        - audio files
      summary: Get a list of audio files
      description: Retrieve a list of all audio files stored in the database
      operationId: getAudioFiles
      responses:
        '200':
          description: List of audio files retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    fileId:
                      type: string
                      description: The ID of the audio file
                      example: 987654321
                    fileName:
                      type: string
                      description: The name of the audio file
                      example: filename.mp3
                    uploadDate:
                      type: string
                      format: date-time
                      description: The date and time the file was uploaded
                      example: 2000-01-01T15:00:00+01
        '500':
          description: An internal server error occurred. Please try again later
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"

  /audiofiles/{fileId}:
    get:
      tags:
        - audio files
      summary: Get an audio file
      description: Find an existing audio file in the database
      operationId: getAudioFile
      parameters:
        - name: fileId
          in: path
          description: ID of the file to retrieve
          required: true
          schema:
            type: string
            example: 987654321
      responses:
        '200':
          description: File retrieved successfully
          content:
            application/octet-stream:
              schema:
                type: string
                format: byte
        '404':
          description: File with the specified ID not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        '500':
          description: An internal server error occurred. Please try again later
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"

    delete:
      tags:
        - audio files
      summary: Delete an audio file
      description: Delete an audio file from the database by file ID
      operationId: deleteAudioFile
      parameters:
        - name: fileId
          in: path
          description: ID of the file to delete
          required: true
          schema:
            type: string
            example: 987654321
      responses:
        '200':
          description: File deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  fileId:
                    type: string
                    description: The ID of the deleted file
                    example: 987654321
        '404':
          description: File with the specified ID not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        '500':
          description: An internal server error occurred. Please try again later
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"

components:
  schemas:
    ErrorDto:
      type: object
      description: The general error model of the application
      properties:
        statusCode:
          type: integer
          description: HTTP status code associated with the error
          example: 404
        userErrorCode:
          type: string
          description: The error code generated by the server and used for UserMessage
          example: 10-500
          pattern: "^[0-9]{2}-[0-9]{3}$"
        errorTime:
          type: string
          format: date-time
          description: Date of the event
          example: 2000-01-01T15:00:00+01
        userMessage:
          type: string
          description: Error text to show to the user
          example: "An error occurred while performing this operation. Error code 10-500"
      required:
        - statusCode
        - userErrorCode
        - errorTime
        - userMessage
    AudioFile:
      type: object
      properties:
        fileId:
          type: integer
          format: int64
          description: ID аудиофайла
        fileName:
          type: string
          description: Название аудиофайла
        uploadDate:
          type: string
          format: date-time
          description: Дата и время загрузки файла
